name: Druid

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'

      - name: Faucet
        run: make faucet

      - name: Lint
        run: make lint

      - name: Test
        run: make test
